# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/pipeline/#customization
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
image: python:3.10-bullseye

stages:
  - test
  - deploy

sast:
  stage: test
include:
- template: Security/SAST.gitlab-ci.yml
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

deploy-to-didata:
  stage: deploy
  rules:
    - if: $CI_COMMIT_BRANCH == "publish" && $CI_PIPELINE_SOURCE == "push"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME == "main" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "publish"
  before_script:
    - apt-get update -qq && apt-get install -y -qq rsync openssh-client
    - eval $(ssh-agent -s)
    - echo "$DIDATA_DEPLOYER_SSH_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
  script:
    - 'echo "Current directory: $PWD"'
    - ls -la
    - |
      if [ "$CI_PIPELINE_SOURCE" = "merge_request_event" ]; then
        echo "This is a merge request. Skipping actual deployment, but running checks..."
        # Add any checks you want to run here
        exit 0
      fi
    - 'rsync -avz --delete-after --exclude=".git/" --exclude=".cache/" --exclude="venv/" --exclude="frontend/node_modules/" . $DIDATA_SERVER_USER@$DIDATA_SERVER_ADDRESS:/tmp/didata_update/'
    - |
      ssh $DIDATA_SERVER_USER@$DIDATA_SERVER_ADDRESS "
        sudo rsync -avz --delete-after /tmp/didata_update/ /var/web_server/htdocs/didata/ &&
        sudo chown -R root:root /var/web_server/htdocs/didata &&
        sudo rm -rf /tmp/didata_update &&
        sudo chmod 755 /var/web_server/htdocs/didata &&
        cd /var/web_server/htdocs/didata &&
        sudo -H pip install -r requirements.txt &&
        sudo python manage.py migrate &&
        sudo systemctl restart didata_gunicorn
      "
  environment:
    name: production
    url: https://didata.tudelft.nl