# Generated by Django 5.0.3 on 2024-05-08 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=100)),
                ('assignment_id', models.CharField(max_length=100)),
                ('result_ids', models.TextField()),
            ],
            options={
                'unique_together': {('course_code', 'assignment_id')},
            },
        ),
    ]
