# Generated by Django 5.0.3 on 2024-06-07 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_assignmentresults'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentresults',
            name='grades',
            field=models.TextField(default=[]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assignmentdata',
            name='data',
            field=models.JSONField(default=dict),
        ),
    ]
