# Generated by Django 5.0.3 on 2024-06-10 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_assignmentresults_grades_alter_assignmentdata_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentresults',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
